"""
Shared compliance / risk-disclosure block used by every outbound report
(main.py stock+commodity report, optionstrategy.py options note,
swing_trade_advisor.py swing note).

Why this exists
----------------
Each report previously carried a single one-line disclaimer buried in the
footer ("...not investment advice"). That's not enough for anything that
looks like a brokerage research note: it doesn't disclose that this isn't
a registered Research Analyst's output, doesn't carry the SEBI-mandated
F&O loss-statistic disclosure, and doesn't separate "this is a risk
warning" from "here's what data this specific run used/missed."

This module centralises that so:
  1. Every report shows the same compliance language (no drift between
     stock / options / swing notes).
  2. The F&O-specific SEBI risk line only appears on reports that actually
     involve derivatives (options note), not on the plain equity report.
  3. The run-specific data-quality note (live search used vs not, NSE feed
     partial, etc.) stays separate from the fixed legal boilerplate, so
     each can be edited independently.

Nothing here claims SEBI Research Analyst registration -- it explicitly
disclaims that, since none of these scripts are produced by a registered
RA/RIA. Do not remove that line; presenting algorithmic output as
registered research advice without a valid SEBI RA number is itself a
compliance problem, not just a wording nicety.
"""

SANS = "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif"

# SEBI mandated this exact statistic be disclosed wherever F&O trading is
# discussed/promoted (circular effective 2023): retail loss rate in the
# equity derivatives segment. Keep this and don't soften it.
SEBI_FNO_RISK_LINE = (
    "As per SEBI-mandated disclosure: nine out of ten individual traders in the "
    "equity Futures &amp; Options segment incurred net losses, with the average "
    "loss significantly exceeding the average profit made by the profitable minority. "
    "Options strategies shown here carry the risk of losing the entire premium paid "
    "(or more, for uncovered/net-short structures) within days."
)

GENERAL_RISK_BULLETS = [
    "Not registered research: this note is generated by an automated technical / "
    "fundamental / sentiment model. It is not produced by a SEBI-registered Research "
    "Analyst or Investment Adviser, and nothing here should be treated as personalised "
    "investment advice.",
    "No guarantee of returns: all targets, stop-losses, entry levels and scores are "
    "model estimates based on historical and current data. Past performance and "
    "back-tested behaviour are not indicative of future results.",
    "Market risk: equity, options, and commodity prices are subject to market risk, "
    "including the possible loss of principal. Leveraged/derivative positions can "
    "lose more than the amount initially committed.",
    "Data risk: figures are sourced from third-party feeds (exchange data, Yahoo "
    "Finance, news APIs) that can be delayed, incomplete, or occasionally wrong. "
    "Always verify prices, OI, IV, and news against your broker's live terminal "
    "before placing any order.",
    "No advisory relationship: this is not a licensed distribution or advisory "
    "activity. Verify everything independently and consult a SEBI-registered "
    "adviser for advice suited to your specific financial situation.",
]


def _bullets_html(items, color="#9AA0AC"):
    lis = "".join(f'<li style="margin:0 0 5px;">{item}</li>' for item in items)
    return (
        f'<ul style="margin:6px 0 0;padding-left:16px;font-family:{SANS};'
        f'font-size:10.5px;line-height:1.55;color:{color};">{lis}</ul>'
    )


def build_compliance_block_html(report_kind, run_note, desk_name="Portfolio Research Desk"):
    """
    Returns the full footer compliance block (a <tr><td>...</td></tr>)
    ready to drop into any of the three report footers in place of the old
    single-paragraph disclaimer.

    report_kind: "equity" | "options" | "swing" | "commodity"
    run_note: the existing run-specific data-quality sentence each report
        already builds (e.g. "Generated using live web search this run --
        see Market Data Inputs above for what was actually used.")
    """
    include_fno_line = report_kind == "options"

    fno_html = (
        f'<p style="margin:8px 0 0;font-family:{SANS};font-size:10.5px;'
        f'line-height:1.6;color:#B0473F;font-weight:600;">{SEBI_FNO_RISK_LINE}</p>'
        if include_fno_line
        else ""
    )

    return f"""
            <tr>
              <td style="padding:16px 28px 22px;border-top:1px solid #EDEAE2;" class="email-padding">
                <p style="margin:0;font-family:{SANS};font-size:11px;line-height:1.6;color:#9AA0AC;">{run_note}</p>
                {fno_html}
                <details style="margin-top:10px;">
                  <summary style="cursor:pointer;font-family:{SANS};font-size:10.5px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em;color:#8A8F9C;">Risk Disclosure &amp; Terms of Use</summary>
                  {_bullets_html(GENERAL_RISK_BULLETS)}
                </details>
                <p style="margin:10px 0 0;font-family:{SANS};font-size:10px;letter-spacing:0.04em;color:#B9BEC7;">&copy; {desk_name} &nbsp;&middot;&nbsp; Automated output, not SEBI-registered research</p>
              </td>
            </tr>
    """